### ISSUE TITLE
No server on port 9100

### ISSUE THREAD

**Issue by H1D** [karma-runner/grunt-karma#49]
Hi! I'm getting this error while trying to run karma with `grunt-karma`:

```
Running tasks: karma:unit:run

Running "karma:unit:run" (karma) task
Verifying property karma.unit exists in config...OK
File: [no files]
There is no server listening on port 9100
```

Seems like `grunt-karma` doesn't start server. While default command does:

```
karma start karma.conf.coffee 
```

Here is part of `grunt` config:

```
    karma:
      options:
        configFile: 'karma.conf.coffee'
        background: true
      unit: {}
      unit_all:
        browsers: ['PhantomJS', 'Chrome', 'Firefox']
```

I'm `0.9.5`
